### ISSUE TITLE
Regression with zwpagelayout MWE

### ISSUE THREAD

**Issue by Quoor8ee** [latex3/iftex#11]
```
\documentclass{article}
\usepackage{zwpagelayout}

\begin{document}
MWE
\end{document}
```
runs normally with the old `iftex` (v0.2 from 2013, as shipped with an early TeXLive 2019 installation from  2019-09-24), but dies horribly on the new code (v1.0c as of TL2019 updates, 2019-11-28):

```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./mwe.tex
LaTeX2e <2019-10-01> patch level 3
(/path/to/texlive/2019-updated/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/10/25 v1.4k Standard LaTeX document class
(/path/to/texlive/2019-updated/texmf-dist/tex/latex/base/size10.clo))
(/path/to/texlive/2019-updated/texmf-dist/tex/latex/zwpagelayout/zwpagel
ayout.sty
(/path/to/texlive/2019-updated/texmf-dist/tex/generic/iftex/ifpdf.sty
(/path/to/texlive/2019-updated/texmf-dist/tex/generic/iftex/iftex.sty))
! Extra \or.
l.195     \or
             
? 
```

I currently don't have the capacity to fully dig into debugging this, but maybe someone here has an opinion on this  unexpected regression within a package of seemingly low complexity. Especially regarding the quickly approaching code freeze for TeXLive 2020.

I'll also inform Zdeněk Wagner, the zwpagelayout author (that pacakge hasn't changed since 2014, but the first lines of zwpagelayout.sty seemingly are a lo-fi hack to provide some iftex-ish conditionals, which might interfere with modern iftex code).

**Comment by davidcarlisle** [comment]
This is really an error in zwpagelayout,  you see the same error in texlive2018 with

```
\documentclass{article}

\newif\ifxetex
\usepackage{zwpagelayout}


\begin{document}

MWE

\end{document}
```

The package guards against `\ifxetex` being defined but uses `\@ifpackageloaded{ifxetex}` which does not work if `\ifxetex` is defined directly as above or in the new code by `iftex.sty` that is implicitly called by the loading of `ifpdf`.

the package could be changed so that the if tokens are safely skipped by changing the initial tests by the following diff

```
$ diff zwpagelayout.sty~ zwpagelayout.sty
23,24c23,24
< \@ifpackageloaded{ifpdf}{}{\IfFileExists{ifpdf.sty}{\RequirePackage{ifpdf}}{\newif\ifpdf}}
< \@ifpackageloaded{ifxetex}{}{\IfFileExists{ifxetex.sty}{\RequirePackage{ifxetex}}{\newif\ifxetex}}
---
> \@ifpackageloaded{ifpdf}{}{\IfFileExists{ifpdf.sty}{\RequirePackage{ifpdf}}{\expandafter\newif\csname ifpdf\endcsname}}
> \@ifpackageloaded{ifxetex}{}{\IfFileExists{ifxetex.sty}{\RequirePackage{ifxetex}}{\expandafter\newif\csname ifxetex\endcsname}}

```

or better it could assume iftex is available and simply use

`\RequirePackage{iftex}`

to define both `\ifpdf` and `\ifxetex`

**Comment by davidcarlisle** [comment]
What I used in the packages split out of the `oberdiek` bundle while removing all uses if the ifpdf and ifluatex packages was

`\RequirePackage{iftex}[2019/11/07]`

so if zwpagelayout used this form it would define all the `\if...`  it needs with a single call, and in the unlikely case that the user has installed a new zwpagelayout but still has the old iftex package that does not define all the if variants, they get a suitable package version warning rather than low level  undefined \ifxxx errors.

**Comment by Quoor8ee** [comment]
Alright, it turned out to be  not an iftex issue, but resolvable on zwpagelayout's side. Version v1.4d on CTAN and TeXLive distribution since today.

Thank you!
